version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cicd-demo
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VERSION=1.0.0
    restart: unless-stopped
